### PR TITLE
Try/run mshots from local docker env local edit

### PR DESCRIPTION
**Pull request by enejb**
This PR fixes a couple of thins that make it easier to develop mShots locally. 

1. Adds a docker volume. So that the files get mounted correctly. And any changes to the PHP files get reflected in the container. 
2. Adds a way to properly configure the memcache url. 

To test.
```
Instructions:
$ docker-compose build
$ docker-compose up
in another window
$ docker exec -it php bash and then ./mshots_ctl.sh start

Load http://localhost:8000/mshots/v1/www.wordpress.com, and this should redirect you to https://wordpress.com/mshots/v1/default/ to show the loading image. Load it again after a few seconds, and you should see the mShot!
```

### CODE REVIEW

**Comment by simison** [comment]
I think there was another PR for the same thing already here: https://github.com/Automattic/mShots/pull/22

**Comment by deBhal** [comment]
I've updated the PR to share the whole `/opt/mshots` directory, and updated the README and npm scripts with some handy docker bits.

I also renamed the service from `php` to `dev`, so: `docker-compose exec dev bash`

@enejb: I didn't mean to trample your work, and I maybe should have made a new PR instead of updating this one. Just say the word and I'll back the changes out into a new branch.

**Comment by enejb** [comment]
Thanks for working on this and making it happen. @deBhal

I tested this by running `npm install` and then `npm start` and it work really well for me. 

Should we add the generated  `.env` , `docker-compose.yml` files  and `stats/` folder to the .gitignore list?

They seem to be environment specific. and got generated when I ran `npm install`

It might be a good idea to get a review from the systems team in case they see something in here that they would like to see changed.

**Comment by andrewserong** [comment]
Thanks again @deBhal this is testing nicely for me, too!

Once the generated files are added to the `.gitignore` like @enejb mentions, I think this looks good to merge into #22, then we can use that PR as the one to get more feedback on before merging, so it's all grouped together?

**Comment by autumnfjeld** [comment]
Fantastic!  And now https://github.com/Automattic/mShots/pull/18 is ready for review.  Great mShots progress @deBhal

**Pull request merged**
